# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'HomeDinner' do
 pod 'NJKWebViewProgress', '~> 0.2.3'
pod 'OpenSSL', '~> 1.0.208'
pod 'MOBFoundation', '~> 2.0.4'
pod 'FMDB', '~> 2.6.2'
pod 'JSONModel', '~> 1.2.0'
pod 'QQ_XGPush'
pod 'MBProgressHUD', '~> 0.9'
pod 'Masonry', '~> 0.6.1'
pod 'SDWebImage', '~> 3.8.0'
pod 'ShareSDK3', '~> 3.3.2'
pod 'ShareSDK3/ShareSDKPlatforms/QQ', '~> 3.3.2'
pod 'ShareSDK3/ShareSDKPlatforms/SinaWeibo', '~> 3.3.2'
pod 'ShareSDK3/ShareSDKPlatforms/WeChat', '~> 3.3.2'
pod 'UIView+FDCollapsibleConstraints', '~> 1.1'
pod 'UITableView+FDTemplateLayoutCell', '~> 1.3'
pod 'AFOnceKit', '~> 1.0.0'
pod 'CRGradientNavigationBar', '~> 0.3.2'
pod 'iCarousel', '~> 1.8.1'
pod 'SMPageControl', '~> 1.2'
pod 'JLRoutes', '~> 1.5.2'
pod 'FDFullscreenPopGesture', :git => 'https://github.com/qpwang/FDFullscreenPopGesture.git', :commit => '3c801945dbe4271e34a7cc96e29be9a11274b6d4'
pod 'MJRefresh', '~> 3.1.0'
pod 'Reachability', '~> 3.2'
#pod 'xg-ios-sdk', :git => 'https://github.com/qpwang/xg-ios-sdk.git', :tag=> 'V2.4.7'
pod 'CustomIOSAlertView', '~> 0.9.3'
pod 'PKYStepper', '~> 0.0.1'
pod 'KVOController', '~> 1.0.3'
pod 'PopMenu', '~> 2.4'
pod 'pop', '~> 1.0.9'
pod 'MWPhotoBrowser', :git => 'https://github.com/you520t/MWPhotoBrowser.git', :commit=>'6e252ae'
pod 'HFTableViewManger', :git => 'https://github.com/helfyz/HFTableViewManger.git', :tag=> '0.0.2'
pod 'HFPrettyTimer', :git => 'https://github.com/helfyz/HFPrettyTimer.git', :tag=> '0.1.0'


end
